# Change these first
owner: OpenAudioMc
repo: status

sites:
  - name: OpenAudioMc-Client
    url: $CLIENT_CHECK_URL
  - name: OpenAudioMc-DocProxy
    url: $DOCPROXY_CHECK_URL
  - name: Craftmend-Accounts
    url: $ACCOUNT_API_CHECK_URL
  - name: Cluster Managment Portal
    url: $MANAGMENT_PORTAL_CHECK_URL
  - name: OpenAudioMc-CDN
    method: POST
    url: $CDN_CHECK_URL
  - name: OpenAudioMc-Discord
    url: $DISCORDBOT_CHECK_URL
  - name: OpenAudioMc-CacheAPI
    url: $CACHEAPI_CHECK_URL
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{ "channel": "oa-monit-target", "message": "pages-ping" }'
  - name: OpenAudioMc-CCA-ImagineFun
    url: $CRCA_CHECK_URL
  - name: OpenAudioMc-CEU-Anouk
    url: $CEU_ANOUK_CHECK_URL
  - name: OpenAudioMc-CEU-Paulo
    url: $CEU_PAULO_CHECK_URL
  - name: OpenAudioMc-CEU-Ben
    url: $CEU_BEN_CHECK_URL
  - name: OpenAudioMc-CEU-Winter
    url: $CEU_WINTER_CHECK_URL
  - name: OpenAudioMc-CEU-Playground
    url: $CEU_PLAYGROUND_CHECK_URL
  - name: OpenAudioMc-CEU-Spring
    url: $CEU_SPRING_CHECK_URL

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: openaudiomc.github.io
  baseUrl: /status
  theme: night
  logoUrl: https://client.openaudiomc.net/assets/logo.png
  name: OpenAudioMc Status
  introTitle: "**OpenAudioMc Status** Is an automated platform polling server status, and opening issues when shit goes haywire."
  introMessage: This data **is not** leading as we have an internal grafana instance hosted externally which triggers main notifications and metrics, but this is just a nice to have.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
